[package]
name = "waveform_db"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
serde = {version = "1.0.145", features = ["derive"]}
indiscriminant = "0.2.0"

[dev-dependencies]
log = "0.4.0"
simple_logger = "2.3.0"
colored = "2"
